const dataWilayah = {
  jateng: {
    Semarang: [
      'Banyumanik',
      'Candisari',
      'Gajah Mungkur',
      'Gayamsari',
      'Genuk',
      'Gunungpati',
      'Mijen',
      'Ngaliyan',
      'Pedurungan',
      'Semarang Barat',
      'Semarang Selatan',
      'Semarang Tengah',
      'Semarang Timur',
      'Semarang Utara',
      'Tembalang',
      'Tugu',
    ],
    Surakarta: [
      'Banjarsari',
      'Jebres',
      'Laweyan',
      'Pasar Kliwon',
      'Serengan',
    ],
    Magelang: [
      'Magelang Selatan',
      'Magelang Tengah',
      'Magelang Utara',
    ],
    Kudus: [
      'Bae',
      'Dawe',
      'Gebog',
      'Jati',
      'Jekulo',
      'Kaliwungu',
      'Kudus Kota',
      'Mejobo',
      'Undaan',
    ],
    Tegal: [
      'Adiwerna',
      'Balapulang',
      'Bojong',
      'Bumijawa',
      'Dukuhturi',
      'Dukuhwaru',
      'Jatinegara',
      'Kedung Banteng',
      'Kramat',
      'Lebaksiu',
      'Margasari',
      'Pagerbarang',
      'Pangkah',
      'Slawi',
      'Surodadi',
      'Talang',
      'Tarub',
      'Warureja',
    ],
  },
  jabar: {
    Bandung: [
      'Andir',
      'Antapani',
      'Arcamanik',
      'Astanaanyar',
      'Babakan Ciparay',
      'Bandung Kidul',
      'Bandung Kulon',
      'Bandung Wetan',
      'Batununggal',
      'Bojongloa Kaler',
      'Bojongloa Kidul',
      'Buahbatu',
      'Cibeunying Kaler',
      'Cibeunying Kidul',
      'Cibiru',
      'Cicendo',
      'Cidadap',
      'Cinambo',
      'Coblong',
      'Gedebage',
      'Kiaracondong',
      'Lengkong',
      'Mandalajati',
      'Panyileukan',
      'Rancasari',
      'Regol',
      'Sukajadi',
      'Sukasari',
      'Sumur Bandung',
      'Ujungberung',
    ],
    Bekasi: [
      'Bantar Gebang',
      'Bekasi Barat',
      'Bekasi Selatan',
      'Bekasi Timur',
      'Bekasi Utara',
      'Jatiasih',
      'Jatisampurna',
      'Medan Satria',
      'Mustika Jaya',
      'Pondok Gede',
      'Pondok Melati',
      'Rawalumbu',
    ],
    Bogor: [
      'Bogor Barat',
      'Bogor Selatan',
      'Bogor Tengah',
      'Bogor Timur',
      'Bogor Utara',
      'Tanah Sereal',
    ],
    Depok: [
      'Beji',
      'Bojongsari',
      'Cilodong',
      'Cimanggis',
      'Cinere',
      'Cipayung',
      'Limo',
      'Pancoran Mas',
      'Sawangan',
      'Sukmajaya',
      'Tapos',
    ],
    Cimahi: [
      'Cimahi Selatan',
      'Cimahi Tengah',
      'Cimahi Utara',
    ],
  },
  jatim: {
    Surabaya: [
      'Asemrowo',
      'Benowo',
      'Bubutan',
      'Bulak',
      'Dukuh Pakis',
      'Gayungan',
      'Genteng',
      'Gubeng',
      'Gunung Anyar',
      'Jambangan',
      'Karang Pilang',
      'Kenjeran',
      'Krembangan',
      'Lakar Santri',
      'Mulyorejo',
      'Pabean Cantian',
      'Pakal',
      'Rungkut',
      'Sambikerep',
      'Sawahan',
      'Semampir',
      'Simokerto',
      'Sukolilo',
      'Sukomanunggal',
      'Tambaksari',
      'Tandes',
      'Tegalsari',
      'Tenggilis Mejoyo',
      'Wiyung',
      'Wonocolo',
      'Wonokromo',
    ],
    Malang: [
      'Blimbing',
      'Kedungkandang',
      'Klojen',
      'Lowokwaru',
      'Sukun',
    ],
    Kediri: [
      'Mojoroto',
      'Kota Kediri',
      'Pesantren',
    ],
    Madiun: [
      'Kartoharjo',
      'Manguharjo',
      'Taman',
    ],
    Mojokerto: [
      'Magersari',
      'Prajurit Kulon',
    ],
  },
  bali: {
    Denpasar: [
      'Denpasar Barat',
      'Denpasar Selatan',
      'Denpasar Timur',
      'Denpasar Utara',
    ],
    Badung: [
      'Abiansemal',
      'Kuta',
      'Kuta Selatan',
      'Kuta Utara',
      'Mengwi',
      'Petang',
    ],
    Gianyar: [
      'Blahbatuh',
      'Gianyar',
      'Payangan',
      'Sukawati',
      'Tampaksiring',
      'Tegallalang',
      'Ubud',
    ],
    Tabanan: [
      'Baturiti',
      'Kediri',
      'Kerambitan',
      'Marga',
      'Penebel',
      'Pupuan',
      'Selemadeg',
      'Selemadeg Barat',
      'Selemadeg Timur',
      'Tabanan',
    ],
    Bangli: [
      'Bangli',
      'Kintamani',
      'Susut',
      'Tembuku',
    ],
  },
  // tambahkan provinsi lainnya dan kota/kabupaten serta kecamatannya
};

export default dataWilayah;
