import { bandeng, gurame, kepiting, lele, patin, productAsin, productAsin2, productAsin3, productAsin4, productAsin5, productBitCabai, productBitHerbal, productBitSayur, productCumi, productCumi2, productCumi3, productCumi4, productCumi5, productJagung, productJagung2, productJagung3, productJagung4, productJagung5, productKedelai, productKedelai2, productKedelai3, productKedelai4, productKedelai5, productKit, productPadi, productPadi2, productPadi3, productPadi4, productPadi5, productRempah, productTelur, productTelur2, productTelur3, productTelur4, productTelur5, productUdang, productUdang2, productUdang3, productUdang4, productUdang5 } from "../assets";

export const products = [
  {
    id: 1,
    productName: 'Padi',
    productImage: [productPadi,productPadi2,productPadi3,productPadi4,productPadi5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Agmart'
  },
  {
    id: 2,
    productName: 'Benih Jagung',
    productImage: [productJagung,productJagung2,productJagung3,productJagung4,productJagung5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Agmart'
  },
  {
    id: 3,
    productName: 'Ikan Asin Segar',
    productImage: [productAsin,productAsin2,productAsin3,productAsin4,productAsin5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 4,
    productName: 'Cumi-cumi Segar',
    productImage: [productCumi,productCumi2,productCumi3,productCumi4,productCumi5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 5,
    productName: 'Kedelai',
    productImage: [productKedelai,productKedelai2,productKedelai3,productKedelai4,productKedelai5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Agmart'
  },
  {
    id: 6,
    productName: 'Telur Ayam',
    productImage: [productTelur,productTelur2,productTelur3,productTelur4,productTelur5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Agmart'
  },
  {
    id: 7,
    productName: 'Udang',
    productImage: [productUdang,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 35000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 8,
    productName: 'Benih ikan lele /kg',
    productImage: [lele,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 29000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 9,
    productName: 'Ikan bandeng',
    productImage: [bandeng,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 31000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 10,
    productName: 'Ikan Gurame',
    productImage: [gurame,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 21000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 11,
    productName: 'Ikan Patin',
    productImage: [patin,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 37000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 12,
    productName: 'Kepiting',
    productImage: [kepiting,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 130000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'marina',
    toko: 'Marinaku'
  },
  {
    id: 13,
    productName: 'Bibit cabai rawit',
    productImage: [productBitCabai,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 19000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Marinaku'
  },
  {
    id: 14,
    productName: 'Bibit sayur pakcoy',
    productImage: [productBitSayur,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 11000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Marinaku'
  },
  {
    id: 15,
    productName: 'kit hidroponik fullset',
    productImage: [productKit,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 535000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Marinaku'
  },
  {
    id: 16,
    productName: 'Paket rempah-rempah',
    productImage: [productRempah,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 45000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Marinaku'
  },
  {
    id: 17,
    productName: 'Bibit tanaman herbal',
    productImage: [productBitHerbal,productUdang2,productUdang3,productUdang4,productUdang5],
    price: 56000,
    discountPercent: 13,
    priceAfterDiscount: 51000,
    sellerCity: 'Aceh',
    rating: 4.3,
    totalSold: 1,
    desc: 'lorem ipsum dolor sit amet',
    category: 'agro',
    toko: 'Marinaku'
  },
]


